# Generated by Django 5.0.1 on 2024-03-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Meter_Address',
        ),
    ]
