# Generated by Django 5.0.1 on 2024-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0002_rename_address_meter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Meter_Address',
        ),
    ]
